FROM golang:1.24 AS build

RUN groupadd -r ubuntu && useradd -m -r -u 1000 -g ubuntu ubuntu && usermod -aG sudo ubuntu

USER ubuntu

WORKDIR /src

COPY . .

RUN env GOOS=wasip1 GOARCH=wasm go build -buildmode=c-shared -o ./http-trace-filter.wasm src/trace/main.go

FROM scratch AS bin

COPY --from=build /src/http-trace-filter.wasm /
